# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/serena/deformation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/serena/deformation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/serena/deformation/CMakeFiles /home/serena/deformation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/serena/deformation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Deformation

# Build rule for target.
Deformation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Deformation
.PHONY : Deformation

# fast build rule for target.
Deformation/fast:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/build
.PHONY : Deformation/fast

camera.o: camera.cpp.o

.PHONY : camera.o

# target to build an object file
camera.cpp.o:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/camera.cpp.o
.PHONY : camera.cpp.o

camera.i: camera.cpp.i

.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s

.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/camera.cpp.s
.PHONY : camera.cpp.s

graph/boundingObject.o: graph/boundingObject.cpp.o

.PHONY : graph/boundingObject.o

# target to build an object file
graph/boundingObject.cpp.o:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/boundingObject.cpp.o
.PHONY : graph/boundingObject.cpp.o

graph/boundingObject.i: graph/boundingObject.cpp.i

.PHONY : graph/boundingObject.i

# target to preprocess a source file
graph/boundingObject.cpp.i:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/boundingObject.cpp.i
.PHONY : graph/boundingObject.cpp.i

graph/boundingObject.s: graph/boundingObject.cpp.s

.PHONY : graph/boundingObject.s

# target to generate assembly for a file
graph/boundingObject.cpp.s:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/boundingObject.cpp.s
.PHONY : graph/boundingObject.cpp.s

graph/deformGraph.o: graph/deformGraph.cpp.o

.PHONY : graph/deformGraph.o

# target to build an object file
graph/deformGraph.cpp.o:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/deformGraph.cpp.o
.PHONY : graph/deformGraph.cpp.o

graph/deformGraph.i: graph/deformGraph.cpp.i

.PHONY : graph/deformGraph.i

# target to preprocess a source file
graph/deformGraph.cpp.i:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/deformGraph.cpp.i
.PHONY : graph/deformGraph.cpp.i

graph/deformGraph.s: graph/deformGraph.cpp.s

.PHONY : graph/deformGraph.s

# target to generate assembly for a file
graph/deformGraph.cpp.s:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/deformGraph.cpp.s
.PHONY : graph/deformGraph.cpp.s

graph/graphvertex.o: graph/graphvertex.cpp.o

.PHONY : graph/graphvertex.o

# target to build an object file
graph/graphvertex.cpp.o:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/graphvertex.cpp.o
.PHONY : graph/graphvertex.cpp.o

graph/graphvertex.i: graph/graphvertex.cpp.i

.PHONY : graph/graphvertex.i

# target to preprocess a source file
graph/graphvertex.cpp.i:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/graphvertex.cpp.i
.PHONY : graph/graphvertex.cpp.i

graph/graphvertex.s: graph/graphvertex.cpp.s

.PHONY : graph/graphvertex.s

# target to generate assembly for a file
graph/graphvertex.cpp.s:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/graphvertex.cpp.s
.PHONY : graph/graphvertex.cpp.s

graph/kdnode.o: graph/kdnode.cpp.o

.PHONY : graph/kdnode.o

# target to build an object file
graph/kdnode.cpp.o:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/kdnode.cpp.o
.PHONY : graph/kdnode.cpp.o

graph/kdnode.i: graph/kdnode.cpp.i

.PHONY : graph/kdnode.i

# target to preprocess a source file
graph/kdnode.cpp.i:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/kdnode.cpp.i
.PHONY : graph/kdnode.cpp.i

graph/kdnode.s: graph/kdnode.cpp.s

.PHONY : graph/kdnode.s

# target to generate assembly for a file
graph/kdnode.cpp.s:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/kdnode.cpp.s
.PHONY : graph/kdnode.cpp.s

graph/kdtree.o: graph/kdtree.cpp.o

.PHONY : graph/kdtree.o

# target to build an object file
graph/kdtree.cpp.o:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/kdtree.cpp.o
.PHONY : graph/kdtree.cpp.o

graph/kdtree.i: graph/kdtree.cpp.i

.PHONY : graph/kdtree.i

# target to preprocess a source file
graph/kdtree.cpp.i:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/kdtree.cpp.i
.PHONY : graph/kdtree.cpp.i

graph/kdtree.s: graph/kdtree.cpp.s

.PHONY : graph/kdtree.s

# target to generate assembly for a file
graph/kdtree.cpp.s:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/kdtree.cpp.s
.PHONY : graph/kdtree.cpp.s

graph/node.o: graph/node.cpp.o

.PHONY : graph/node.o

# target to build an object file
graph/node.cpp.o:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/node.cpp.o
.PHONY : graph/node.cpp.o

graph/node.i: graph/node.cpp.i

.PHONY : graph/node.i

# target to preprocess a source file
graph/node.cpp.i:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/node.cpp.i
.PHONY : graph/node.cpp.i

graph/node.s: graph/node.cpp.s

.PHONY : graph/node.s

# target to generate assembly for a file
graph/node.cpp.s:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/graph/node.cpp.s
.PHONY : graph/node.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/main.cpp.s
.PHONY : main.cpp.s

mesh.o: mesh.cpp.o

.PHONY : mesh.o

# target to build an object file
mesh.cpp.o:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/mesh.cpp.o
.PHONY : mesh.cpp.o

mesh.i: mesh.cpp.i

.PHONY : mesh.i

# target to preprocess a source file
mesh.cpp.i:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/mesh.cpp.i
.PHONY : mesh.cpp.i

mesh.s: mesh.cpp.s

.PHONY : mesh.s

# target to generate assembly for a file
mesh.cpp.s:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/mesh.cpp.s
.PHONY : mesh.cpp.s

model.o: model.cpp.o

.PHONY : model.o

# target to build an object file
model.cpp.o:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/model.cpp.o
.PHONY : model.cpp.o

model.i: model.cpp.i

.PHONY : model.i

# target to preprocess a source file
model.cpp.i:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/model.cpp.i
.PHONY : model.cpp.i

model.s: model.cpp.s

.PHONY : model.s

# target to generate assembly for a file
model.cpp.s:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/model.cpp.s
.PHONY : model.cpp.s

resource_manager.o: resource_manager.cpp.o

.PHONY : resource_manager.o

# target to build an object file
resource_manager.cpp.o:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/resource_manager.cpp.o
.PHONY : resource_manager.cpp.o

resource_manager.i: resource_manager.cpp.i

.PHONY : resource_manager.i

# target to preprocess a source file
resource_manager.cpp.i:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/resource_manager.cpp.i
.PHONY : resource_manager.cpp.i

resource_manager.s: resource_manager.cpp.s

.PHONY : resource_manager.s

# target to generate assembly for a file
resource_manager.cpp.s:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/resource_manager.cpp.s
.PHONY : resource_manager.cpp.s

shader.o: shader.cpp.o

.PHONY : shader.o

# target to build an object file
shader.cpp.o:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/shader.cpp.o
.PHONY : shader.cpp.o

shader.i: shader.cpp.i

.PHONY : shader.i

# target to preprocess a source file
shader.cpp.i:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/shader.cpp.i
.PHONY : shader.cpp.i

shader.s: shader.cpp.s

.PHONY : shader.s

# target to generate assembly for a file
shader.cpp.s:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/shader.cpp.s
.PHONY : shader.cpp.s

stb_image.o: stb_image.cpp.o

.PHONY : stb_image.o

# target to build an object file
stb_image.cpp.o:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/stb_image.cpp.o
.PHONY : stb_image.cpp.o

stb_image.i: stb_image.cpp.i

.PHONY : stb_image.i

# target to preprocess a source file
stb_image.cpp.i:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/stb_image.cpp.i
.PHONY : stb_image.cpp.i

stb_image.s: stb_image.cpp.s

.PHONY : stb_image.s

# target to generate assembly for a file
stb_image.cpp.s:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/stb_image.cpp.s
.PHONY : stb_image.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/test.cpp.s
.PHONY : test.cpp.s

texture.o: texture.cpp.o

.PHONY : texture.o

# target to build an object file
texture.cpp.o:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/texture.cpp.o
.PHONY : texture.cpp.o

texture.i: texture.cpp.i

.PHONY : texture.i

# target to preprocess a source file
texture.cpp.i:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/texture.cpp.i
.PHONY : texture.cpp.i

texture.s: texture.cpp.s

.PHONY : texture.s

# target to generate assembly for a file
texture.cpp.s:
	$(MAKE) -f CMakeFiles/Deformation.dir/build.make CMakeFiles/Deformation.dir/texture.cpp.s
.PHONY : texture.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Deformation"
	@echo "... edit_cache"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... graph/boundingObject.o"
	@echo "... graph/boundingObject.i"
	@echo "... graph/boundingObject.s"
	@echo "... graph/deformGraph.o"
	@echo "... graph/deformGraph.i"
	@echo "... graph/deformGraph.s"
	@echo "... graph/graphvertex.o"
	@echo "... graph/graphvertex.i"
	@echo "... graph/graphvertex.s"
	@echo "... graph/kdnode.o"
	@echo "... graph/kdnode.i"
	@echo "... graph/kdnode.s"
	@echo "... graph/kdtree.o"
	@echo "... graph/kdtree.i"
	@echo "... graph/kdtree.s"
	@echo "... graph/node.o"
	@echo "... graph/node.i"
	@echo "... graph/node.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mesh.o"
	@echo "... mesh.i"
	@echo "... mesh.s"
	@echo "... model.o"
	@echo "... model.i"
	@echo "... model.s"
	@echo "... resource_manager.o"
	@echo "... resource_manager.i"
	@echo "... resource_manager.s"
	@echo "... shader.o"
	@echo "... shader.i"
	@echo "... shader.s"
	@echo "... stb_image.o"
	@echo "... stb_image.i"
	@echo "... stb_image.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
	@echo "... texture.o"
	@echo "... texture.i"
	@echo "... texture.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

